dist: trusty

language: php

php:
  - 7.2

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

notifications:
  slack: ahgiles:oJwO2Mq7n5V8qmftu2RrtKIb

addons:
  sonarcloud:
    organization: "ciroges-github"
    token:
      secure: 7269aada01e4b77f19f372f4809c085ad8018d83
jdk:
  - oraclejdk8
script:
  - sonar-scanner
