language: php

php:
  - 5.6

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

 notifications:
    slack: ahgiles:oJwO2Mq7n5V8qmftu2RrtKIb  
